version: '3.7'
services:
    app:
        build:
            context: .
        volumes:
            - .:/middleman
        ports:
            - "4567:4567"
        command:
            - /bin/sh
            - -c
            - |
              bundle install
              bundle exec middleman build --verbose
              bundle exec middleman server